/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiagramaRouteImport } from './routes/diagrama'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiExamRouteImport } from './routes/api/exam'
import { Route as ApiExamGradeRouteImport } from './routes/api/exam-grade'
import { Route as ApiStatusRouteImport } from './routes/api/status'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagramaRoute = DiagramaRouteImport.update({
  id: '/diagrama',
  path: '/diagrama',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExamRoute = ApiExamRouteImport.update({
  id: '/api/exam',
  path: '/api/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExamGradeRoute = ApiExamGradeRouteImport.update({
  id: '/api/exam-grade',
  path: '/api/exam-grade',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatusRoute = ApiStatusRouteImport.update({
  id: '/api/status',
  path: '/api/status',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagrama': typeof DiagramaRoute
  '/api/chat': typeof ApiChatRoute
  '/api/exam': typeof ApiExamRoute
  '/api/exam-grade': typeof ApiExamGradeRoute
  '/api/status': typeof ApiStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagrama': typeof DiagramaRoute
  '/api/chat': typeof ApiChatRoute
  '/api/exam': typeof ApiExamRoute
  '/api/exam-grade': typeof ApiExamGradeRoute
  '/api/status': typeof ApiStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagrama': typeof DiagramaRoute
  '/api/chat': typeof ApiChatRoute
  '/api/exam': typeof ApiExamRoute
  '/api/exam-grade': typeof ApiExamGradeRoute
  '/api/status': typeof ApiStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagrama'
    | '/api/chat'
    | '/api/exam'
    | '/api/exam-grade'
    | '/api/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagrama'
    | '/api/chat'
    | '/api/exam'
    | '/api/exam-grade'
    | '/api/status'
  id:
    | '__root__'
    | '/'
    | '/diagrama'
    | '/api/chat'
    | '/api/exam'
    | '/api/exam-grade'
    | '/api/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagramaRoute: typeof DiagramaRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiExamRoute: typeof ApiExamRoute
  ApiExamGradeRoute: typeof ApiExamGradeRoute
  ApiStatusRoute: typeof ApiStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagrama': {
      id: '/diagrama'
      path: '/diagrama'
      fullPath: '/diagrama'
      preLoaderRoute: typeof DiagramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exam': {
      id: '/api/exam'
      path: '/api/exam'
      fullPath: '/api/exam'
      preLoaderRoute: typeof ApiExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exam-grade': {
      id: '/api/exam-grade'
      path: '/api/exam-grade'
      fullPath: '/api/exam-grade'
      preLoaderRoute: typeof ApiExamGradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/status': {
      id: '/api/status'
      path: '/api/status'
      fullPath: '/api/status'
      preLoaderRoute: typeof ApiStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagramaRoute: DiagramaRoute,
  ApiChatRoute: ApiChatRoute,
  ApiExamRoute: ApiExamRoute,
  ApiExamGradeRoute: ApiExamGradeRoute,
  ApiStatusRoute: ApiStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
